#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/build_mitgcm_front,v 1.1 2008/02/16 18:40:03 jmc Exp $


cat <<EOF
==========================================================
Building the mitgcm.org front pages:
==========================================================

EOF
#export CVSROOT='/u/gcmpack' 
#cd /u/u2/jmc/testing/front_content && cvs -q update -P -d
cd /u/u2/jmc/testing/front_content && make install

