#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/daily_snapshot,v 1.2 2008/02/29 01:51:27 jmc Exp $

# download or update several dir. which are used for:
# - front_page building
# - processing testing emails (-> testing page, part of front_page building)
# - making a daily tar file of source code

export CVSROOT=/u/gcmpack

#- update scripts with explicit path:
echo -n 'Update dir:'
cd /u/u2/jmc/testing/scripts && pwd && cvs -q update -P -d

#-- update tools/mpack-1.6 dir :
tmpFil=/tmp/TTT.daily_snapshot.$$
exe=munpack
cd /u/u2/jmc/testing/tools_mpack
echo -n 'Update dir:' ; pwd
chg=`cvs -q update -P -d | tee $tmpFil | sed '/^?/d' | wc -l`
#echo "chg ='$chg'"
cat $tmpFil ; rm -f $tmpFil
if test "x$chg" != x0 ; then 
  if test -f $exe ; then echo " removing: $exe force re-build." ; fi 
  rm -f $exe 
fi

#- update front-page building dir:
echo -n 'Update dir:'
cd /u/u2/jmc/testing/front_content && pwd && cvs -q update -P -d

#-- clean-up old log files:
cd /u/u2/jmc/testing/logs
n=$(( `ls bld_manual.* | wc -l` - 10 ))
if test $n -gt 0 ; then
  echo -n ' remove files: ' 
    ls -lt bld_manual.* | tail -"$n"
    ls -t  bld_manual.* | tail -"$n" | xargs rm -f
fi


umask 0002

echo 'Changing directory to /u/httpd/html/download/daily_snapshot'
cd /u/httpd/html/download/daily_snapshot
test -e MITgcm  &&  rm -rf MITgcm

echo 'Checking out MITgcm...'
cvs co -P MITgcm > /dev/null 2>&1
#chgrp gcmpack MITgcm
#chmod 775 MITgcm

echo 'Creating the tar file...'
rm -rf MITgcm_ss_*
tname='MITgcm_ss_'`date +%Y%m%d`'.tar.gz'
tar -czf $tname ./MITgcm
#chmod 664 $tname
ls -l $tname

echo 'Done!'

