#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/daily_update,v 1.2 2009/06/05 21:00:54 jmc Exp $

# update several dir. which are used for:
# - front_page building
# - processing testing emails (-> testing page, part of front_page building)
# - making a daily tar file of source code

export CVSROOT=/u/gcmpack

#- update scripts with explicit path:
echo -n 'Update dir:'
cd /u/u2/jmc/testing/scripts && pwd && cvs -q update -P -d

#- update csail testing scripts:
echo -n 'Update dir:'
cd /u/u2/jmc/testing/csail && pwd && cvs -q update -P -d

#-- update tools/mpack-1.6 dir :
tmpFil=/tmp/TTT.daily_snapshot.$$
exe=munpack
cd /u/u2/jmc/testing/tools_mpack
echo -n 'Update dir:' ; pwd
chg=`cvs -q update -P -d | tee $tmpFil | sed '/^?/d' | wc -l`
#echo "chg ='$chg'"
cat $tmpFil ; rm -f $tmpFil
if test "x$chg" != x0 ; then
  if test -f $exe ; then echo " removing: $exe force re-build." ; fi
  rm -f $exe
fi

#- update front-page building dir:
echo -n 'Update dir:'
cd /u/u2/jmc/testing/front_content && pwd && cvs -q update -P -d

#-- clean-up old log files:
cd /u/u2/jmc/testing/logs
n=$(( `ls bld_manual.* | wc -l` - 10 ))
if test $n -gt 0 ; then
  echo -n ' remove files: '
    ls -lt bld_manual.* | tail -"$n"
    ls -t  bld_manual.* | tail -"$n" | xargs rm -f
fi
p=`ls check_outp_*.txt_bak | wc -l`
n=$(( `ls check_outp_*.txt | wc -l` - 15 ))
if test $p -gt 0 -o $n -gt 0 ; then echo -n ' remove files: ' ; fi
if test $p -gt 0 ; then
  ls    check_outp_*.txt_bak
  rm -f check_outp_*.txt_bak
fi
if test $n -gt 0 ; then
    ls -lt check_outp_*.txt | tail -"$n"
    ls -t  check_outp_*.txt | tail -"$n" | xargs rm -f
fi

