#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/daily_update,v 1.4 2018/01/08 23:51:57 jmc Exp $

# Run in: ~/testing/ to update several dir. which are used for:
# - front_page building
# - processing testing emails (-> testing page, part of front_page building)
# - making a daily tar file of source code

export CVS_RSH=ssh
export CVSROOT=':ext:jmc@mitgcm.org:/u/gcmpack'

#- update scripts dir:
if test -d scripts ; then
 echo -n 'Update dir: '
 ( cd scripts && pwd && cvs -q update -P -d )
fi

#- update ref_machine testing scripts:
if test -d ref_machine ; then
 echo -n 'Update dir: '
 ( cd ref_machine && pwd && cvs -q update -P -d )
fi

#-- update tools/mpack-1.6 dir:
if test -d tools_mpack ; then
 echo -n 'Update dir: '
 tmpFil=/tmp/TTT.daily_snapshot.$$
 exe=munpack
 ( cd tools_mpack ; pwd
   chg=`cvs -q update -P -d | tee $tmpFil | sed '/^?/d' | wc -l`
  #echo "chg ='$chg'"
   cat $tmpFil ; rm -f $tmpFil
   if test "x$chg" != x0 ; then
     if test -f $exe ; then echo " removing: $exe force re-build." ; fi
     rm -f $exe
   fi
 )
fi

#- update front-page building dir:
if test -d front_content ; then
 echo -n 'Update dir: '
 ( cd front_content && pwd && cvs -q update -P -d )
fi

#-- clean-up old log files:
cd logs
n=$(( `ls bld_manual.* 2>/dev/null | wc -l` - 10 ))
if test $n -gt 0 ; then
  echo -n ' remove files: '
    ls -lt bld_manual.* | tail -"$n"
    ls -t  bld_manual.* | tail -"$n" | xargs rm -f
fi
p=`ls check_outp_*.txt_bak 2>/dev/null | wc -l`
n=$(( `ls check_outp_*.txt 2>/dev/null | wc -l` - 15 ))
if test $p -gt 0 -o $n -gt 0 ; then echo -n ' remove files: ' ; fi
if test $p -gt 0 ; then
  ls    check_outp_*.txt_bak
  rm -f check_outp_*.txt_bak
fi
if test $n -gt 0 ; then
    ls -lt check_outp_*.txt | tail -"$n"
    ls -t  check_outp_*.txt | tail -"$n" | xargs rm -f
fi
