#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/daily_tarfile,v 1.2 2009/07/10 00:27:16 jmc Exp $

# download the source code and make a tar file

export CVSROOT=/u/gcmpack

umask 0002

echo 'Changing dir. to /u/httpd/html/download/daily_snapshot'
cd /u/httpd/html/download/daily_snapshot
outp=$?
if test $outp != 0 ; then
   echo " Error in cd : $outp"
   exit
fi
test -e MITgcm  &&  rm -rf MITgcm

echo 'Checking out MITgcm...'
cvs co -P MITgcm > /dev/null 2>&1
#chgrp gcmpack MITgcm
#chmod 775 MITgcm

echo 'Creating the tar file...'
rm -rf MITgcm_ss_*
tname='MITgcm_ss_'`date +%Y%m%d`'.tar.gz'
tar -czf $tname ./MITgcm
#chmod 664 $tname
ls -l $tname

echo 'Done!'

#-- test for new checkpoint
cd ..
version_file="daily_snapshot/MITgcm/doc/tag-index"
backupDir="other_checkpoints" 
if test -f $version_file ; then
    thischkpt=`awk '/^checkpoint/{print $1; exit}' $version_file`
    short=`echo $thischkpt | sed 's/checkpoint/c/'`
    chkptar="MITgcm_$short"
    if test -f $chkptar.tar.gz ; then
      echo "tar file ($chkptar) exist for current tag: $thischkpt"
    else
      echo -n "Checking out $thischkpt ..."
      rm -f checkout.out checkout.err
      cvs co -P -d $chkptar -r $thischkpt MITgcm 1> checkout.out 2> checkout.err
      outp=$?
      if test $outp != 0 ; then
         echo " Error in cvs checkout: $outp"
         cat checkout.err
         exit
      fi
      echo -n " ; making tar file ... "
      rm -f checkout.out checkout.err
      tar -cf $chkptar.tar $chkptar
      outp=$?
      if test $outp != 0 ; then
         echo " Error in tar command: $outp"
         exit
      else
         echo " Done"
         rm -r -f $chkptar
      fi
      gzip $chkptar.tar
      ls -l $chkptar.tar*
      #-- move previous tar file to backupDir
      listTar=`ls MITgcm_c*.tar.gz`
      if test -d $backupDir ; then
        for xx in $listTar ; do
          if test $xx != $chkptar.tar.gz ; then
            if test -f other_checkpoints/$xx ; then
              echo "error: $backupDir/$xx already exist" 
            else
              echo " mv $xx $backupDir"
              mv $xx $backupDir
            fi
          fi
        done
      else
         echo " no dir: $backupDir"
         exit
      fi
    fi
fi

