#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/prc_tr_emails,v 1.1 2018/01/03 23:19:50 jmc Exp $

#cat <<EOF
#==========================================================
#Parsing MITgcm testing emails :
#==========================================================
#
#EOF

#-- build munpack if needed:
unpck=/home/jm_c/testing/tools_mpack/munpack
if test ! -x $unpck ; then
 MPACKDIR=`dirname $unpck`
 cd $MPACKDIR
 ./configure && make
fi

#-- create a daily log file (if not already there)
cd /home/jm_c/testing/logs
logpfx="prc_emails_" ; sfx=`date +%m%d`
logfile="../logs/${logpfx}$sfx"
if test -e $logfile ; then :
else
#-- clean-up old log files:
  echo -n '-- in dir: ' ; pwd
  n=$(( `ls ${logpfx}* | wc -l` - 10 ))
  if test $n -gt 0 ; then
  echo -n ' remove files: '
    ls -lt ${logpfx}* | tail -"$n"
    ls -t  ${logpfx}* | tail -"$n" | xargs rm -f
  fi
  echo ' create new log file:' $logfile
  touch $logfile
  echo "This log file was created by:" `hostname` " on:" `date` >> $logfile
fi

#-- get and parse emails :
cd /home/jm_c/testing/front_content && ./get+parse_msg -u $unpck -a jmc@ocean.mit.edu >> $logfile 2>&1
#cd /home/jm_c/testing/temp && ./get+parse_msg -u $unpck -a jmc@ocean.mit.edu >> $logfile 2>&1
