#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/process_emails,v 1.9 2018/01/11 21:59:04 jmc Exp $

#cat <<EOF
#==========================================================
#Parsing MITgcm testing emails :
#==========================================================
#
#EOF

#-- build munpack if needed:
unpck=$HOME/testing/tools_mpack/munpack
if test ! -x $unpck ; then
 MPACKDIR=`dirname $unpck`
 cd $MPACKDIR
 ./configure && make
fi
unpck=$HOME/testing/munpack.$HOSTTYPE
#ls -l $unpck

#-- create a daily log file (if not already there)
cd $HOME/testing/logs
logpfx="prc_emails_" ; sfx=`date +%m%d`
logfile="../logs/${logpfx}$sfx"
if test -e $logfile ; then :
else
#-- clean-up old log files:
  echo -n '-- in dir: ' ; pwd
  n=$(( `ls ${logpfx}* | wc -l` - 10 ))
  if test $n -gt 0 ; then
  echo -n ' remove files: '
    ls -lt ${logpfx}* | tail -"$n"
    ls -t  ${logpfx}* | tail -"$n" | xargs rm -f
  fi
  echo ' create new log file:' $logfile
  touch $logfile
  echo "Log file created from '"`hostname`"' by '$USER' on:" `date` >> $logfile
  chmod 664 $logfile
fi

#-- parse emails :
cd $HOME/testing/front_content && ./parse_emails -u $unpck -a jmc@ocean.mit.edu >> $logfile 2>&1
#cd $HOME/testing/temp && ./parse_emails -u $unpck -a jmc@ocean.mit.edu >> $logfile 2>&1
