#! /usr/bin/env bash

# $Header: /u/gcmpack/mitgcm.org/scripts/process_emails,v 1.3 2008/02/27 01:42:56 jmc Exp $

#cat <<EOF
#==========================================================
#Parsing MITgcm testing emails :
#==========================================================
#
#EOF

#-- build munpack if needed:
unpck=/u/u2/jmc/testing/tools_mpack/munpack
if test ! -x $unpck ; then
 MPACKDIR=`dirname $unpck`
 cd $MPACKDIR
 ./configure && make
fi

#-- parse emails :
cd /u/u2/jmc/testing/front_content && ./parse_emails -u $unpck -v -a jmc@ocean.mit.edu

