#!/bin/sh

findnode()
{
echo ln -s `egrep "$2" node*.html | sed 's/:.*//'` $1 1>&2
ln -sf `egrep "$2" node*.html | sed 's/:.*//'` $1 1>&2
}

cd manual
findnode contents.html "^Contents"
findnode overview.html "^1.[0-9] Introduction"
findnode discrete.html "^2. Discretization and Algorithm"
findnode horizcurve.html "^2.* Vector invariant"
findnode fvol.html "^2.* The finite volume method:"
findnode getting.html "^3. Getting started and using the MITgcm"
findnode sarch.html "^4.1 Overall architectural goals"
findnode wrapper.html "^4.2 WRAPPER"
findnode targethw.html "^4.2.* Target hardware"
findnode tiles.html    "^4.* Tiles<"
findnode using_wrapper.html "^4.3 Using the WRAPPER"
findnode autodiff.html "^5. Automatic Differentiation"
findnode packages.html "^6. Physical Parameterization and Packages"
findnode diags.html "^7. Diagnostiacs and tools"
findnode ecco.html "^8. Interface with ECCO"

findnode obtaining.html "^3.[0-9] Obtaining the code"
findnode compiling.html "^3.[0-9] Building the code"
findnode running.html "^3.[0-9] Running the model"
findnode looking.html "^3.[0-9].[0-9] Looking at the output"
findnode doing.html "^3.[0-9] Doing it yourself: customizing the code"

findnode eg_barotrop.html "^3.[0-9] Example: Barotropic Ocean Gyre"
findnode eg_baroclin.html "^3.[0-9] Example: Four layer Baroclinic"
findnode global4x4.html "^3.10 Example: 4"
findnode sens.html "^3.[0-9]* Example: Centenial Time"

findnode illustrations.html "^1.[0-9] Illustrations of the model"
findnode continuous.html "^1.[0-9] Continuous equations"
findnode atmos.html "^1.[0-9].[0-9] Global atmosphere:"
findnode ocean.html "^1.[0-9].[0-9] Global ocean circulation"
findnode nonhydro.html "^1.[0-9].[0-9] Convection and mixing over topography"
findnode paramsens.html "^1.[0-9].[0-9] Parameter sensitivity"
